apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "auth.fullname" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "auth.selectorLabels" . | nindent 6 }}
