apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "management.fullname" . }}
  labels:
    {{- include "management.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "management.selectorLabels" . | nindent 6 }}
