apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "scanner.fullname" . }}
  labels:
    {{- include "scanner.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "scanner.selectorLabels" . | nindent 6 }}
