apiVersion: v1
kind: Service
metadata:
  name: {{ include "scanner.fullname" . }}
  labels:
    {{- include "scanner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "scanner.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
