replicaCount: 2

image:
  repository: ghcr.io/steveokay/registry-signer
  pullPolicy: IfNotPresent
  tag: ""

service:
  httpPort: 8080
  grpcPort: 50051

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

serviceAccount:
  create: true
  name: ""

secretName: registry-signer-secrets

env:
  LOG_LEVEL: info
  LOG_FORMAT: json
  GRPC_ADDR: ":50051"
  HTTP_ADDR: ":8080"
  OTEL_SERVICE_NAME: registry-signer

nodeSelector: {}
tolerations: []
affinity: {}
