/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardRepoNameRouteImport } from './routes/_authenticated/dashboard/$repoName'
import { Route as AuthenticatedDashboardRepoNameIndexRouteImport } from './routes/_authenticated/dashboard/$repoName/index'
import { Route as AuthenticatedDashboardRepoNameScanRouteImport } from './routes/_authenticated/dashboard/$repoName/scan'
import { Route as AuthenticatedDashboardRepoNameBuildsRouteImport } from './routes/_authenticated/dashboard/$repoName/builds'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRepoNameRoute =
  AuthenticatedDashboardRepoNameRouteImport.update({
    id: '/$repoName',
    path: '/$repoName',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRepoNameIndexRoute =
  AuthenticatedDashboardRepoNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRepoNameRoute,
  } as any)
const AuthenticatedDashboardRepoNameScanRoute =
  AuthenticatedDashboardRepoNameScanRouteImport.update({
    id: '/scan',
    path: '/scan',
    getParentRoute: () => AuthenticatedDashboardRepoNameRoute,
  } as any)
const AuthenticatedDashboardRepoNameBuildsRoute =
  AuthenticatedDashboardRepoNameBuildsRouteImport.update({
    id: '/builds',
    path: '/builds',
    getParentRoute: () => AuthenticatedDashboardRepoNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/$repoName': typeof AuthenticatedDashboardRepoNameRouteWithChildren
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/$repoName/builds': typeof AuthenticatedDashboardRepoNameBuildsRoute
  '/dashboard/$repoName/scan': typeof AuthenticatedDashboardRepoNameScanRoute
  '/dashboard/$repoName/': typeof AuthenticatedDashboardRepoNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/$repoName/builds': typeof AuthenticatedDashboardRepoNameBuildsRoute
  '/dashboard/$repoName/scan': typeof AuthenticatedDashboardRepoNameScanRoute
  '/dashboard/$repoName': typeof AuthenticatedDashboardRepoNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/$repoName': typeof AuthenticatedDashboardRepoNameRouteWithChildren
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/$repoName/builds': typeof AuthenticatedDashboardRepoNameBuildsRoute
  '/_authenticated/dashboard/$repoName/scan': typeof AuthenticatedDashboardRepoNameScanRoute
  '/_authenticated/dashboard/$repoName/': typeof AuthenticatedDashboardRepoNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/$repoName'
    | '/dashboard/'
    | '/dashboard/$repoName/builds'
    | '/dashboard/$repoName/scan'
    | '/dashboard/$repoName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/$repoName/builds'
    | '/dashboard/$repoName/scan'
    | '/dashboard/$repoName'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/$repoName'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/$repoName/builds'
    | '/_authenticated/dashboard/$repoName/scan'
    | '/_authenticated/dashboard/$repoName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/$repoName': {
      id: '/_authenticated/dashboard/$repoName'
      path: '/$repoName'
      fullPath: '/dashboard/$repoName'
      preLoaderRoute: typeof AuthenticatedDashboardRepoNameRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/$repoName/': {
      id: '/_authenticated/dashboard/$repoName/'
      path: '/'
      fullPath: '/dashboard/$repoName/'
      preLoaderRoute: typeof AuthenticatedDashboardRepoNameIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRepoNameRoute
    }
    '/_authenticated/dashboard/$repoName/scan': {
      id: '/_authenticated/dashboard/$repoName/scan'
      path: '/scan'
      fullPath: '/dashboard/$repoName/scan'
      preLoaderRoute: typeof AuthenticatedDashboardRepoNameScanRouteImport
      parentRoute: typeof AuthenticatedDashboardRepoNameRoute
    }
    '/_authenticated/dashboard/$repoName/builds': {
      id: '/_authenticated/dashboard/$repoName/builds'
      path: '/builds'
      fullPath: '/dashboard/$repoName/builds'
      preLoaderRoute: typeof AuthenticatedDashboardRepoNameBuildsRouteImport
      parentRoute: typeof AuthenticatedDashboardRepoNameRoute
    }
  }
}

interface AuthenticatedDashboardRepoNameRouteChildren {
  AuthenticatedDashboardRepoNameBuildsRoute: typeof AuthenticatedDashboardRepoNameBuildsRoute
  AuthenticatedDashboardRepoNameScanRoute: typeof AuthenticatedDashboardRepoNameScanRoute
  AuthenticatedDashboardRepoNameIndexRoute: typeof AuthenticatedDashboardRepoNameIndexRoute
}

const AuthenticatedDashboardRepoNameRouteChildren: AuthenticatedDashboardRepoNameRouteChildren =
  {
    AuthenticatedDashboardRepoNameBuildsRoute:
      AuthenticatedDashboardRepoNameBuildsRoute,
    AuthenticatedDashboardRepoNameScanRoute:
      AuthenticatedDashboardRepoNameScanRoute,
    AuthenticatedDashboardRepoNameIndexRoute:
      AuthenticatedDashboardRepoNameIndexRoute,
  }

const AuthenticatedDashboardRepoNameRouteWithChildren =
  AuthenticatedDashboardRepoNameRoute._addFileChildren(
    AuthenticatedDashboardRepoNameRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardRepoNameRoute: typeof AuthenticatedDashboardRepoNameRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardRepoNameRoute:
      AuthenticatedDashboardRepoNameRouteWithChildren,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
