apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gc.fullname" . }}
  labels:
    {{- include "gc.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gc.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    # DNS
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    # Internal services (metadata gRPC, storage gRPC)
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
