apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "signer.fullname" . }}
  labels:
    {{- include "signer.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "signer.selectorLabels" . | nindent 6 }}
